// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdllddffiihycbtgawbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkbGxkZGZmaWloeWNidGdhd2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTIwNzEsImV4cCI6MjA3MTI2ODA3MX0.Mvq3hlEWx-e9I6J0Xhrd4piPzVJalJf-Ppm6dgQfO7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});